### ISSUE TITLE
Scaling factors for MDR in codadef EPS-20190617

### ISSUE THREAD

**Issue by mcartwright1** [stcorp/codadef-eps#1]
The latest codadef source code (EPS-20190617) (1) appears to contain discrepancies in the scaling factors and units for the most recent Product Format Specification (2) for atmospheric water vapour, atmospheric ozone and integrated ozone. This information is in the IASI_MDR_L2_v4.xml file. There is potential there are others, but I have not checked as of yet.

(1) https://github.com/stcorp/codadef-eps/releases
(2) https://www.eumetsat.int/website/home/Data/TechnicalDocuments/index.html - IASI Level 2 Product Format Specification - V9B

I can't quite pin-point when the change in the scaling factors occurred but it was between version 3 and version 4 of the MDR product.

**Comment by svniemeijer** [comment]
The scaling factors were indeed incorrect. The change was with the introduction of PFS V9.
There were also a few scaling factors of other variables incorrect.
All scaling factors have been corrected and a new codadef has been made available.

**Comment by mcartwright1** [comment]
Excellent, thank you very much
